version: 2
jobs:
  build:
    branches:
      only:
        - Assignment5
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt update && sudo apt install wget zip unzip python2.7 python-pip -y 
      - run:
          name: Install Dotnet
          command: wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb &&sudo dpkg -i packages-microsoft-prod.deb && sudo apt-get install apt-transport-https -y && sudo apt-get update && sudo apt-get install dotnet-sdk-2.2 -y
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Build Artifact
          command: |
            cd webapp
            ls -al
            cd NoteApp_Production
            pwd
            dotnet restore
            dotnet build
            dotnet ef migrations add ${CIRCLE_BUILD_NUM}
            dotnet publish -o aws
            cd ../
            cd ../
            cd aws/
            ls -al

