version: 2
jobs:
  build:
    branches:
      only:
        - Assignment5
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt update && sudo apt install wget zip unzip python2.7 python-pip -y && sudo apt install -f -y && sudo apt update && sudo dpkg --configure -a && sudo apt install apt-transport-https -y
      - run:
          name: Install Dotnet
          command: wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb && sudo apt-get install software-properties-common -y && sudo apt-get update  && sudo apt-get install dotnet-runtime-2.2 -y &&  sudo apt-get install aspnetcore-runtime-2.2 -y && sudo apt-get install dotnet-sdk-2.2 -y

