version: 2
jobs:
  build:
    branches:
      only:
        - Assignment5
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y
      - run:
          name: Install Dotnet
          command: wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb -y

